# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.21
# 
# >> macros
%define cups_serverbin %{_exec_prefix}/lib/cups
# << macros

Name:       cups
Summary:    Common Unix Printing System
Version:    1.4.4
Release:    5
Group:      System/Daemons
License:    GPLv2
URL:        http://www.cups.org/
Source0:    http://ftp.easysw.com/pub/cups/%{version}/cups-%{version}-source.tar.bz2
Source1:    cupsprinter.png
Source2:    cups-libusb.rules
Source3:    pstopdf
Source4:    cups-lpd
Source5:    cups.logrotate
Source6:    ncp.backend
Source7:    cups.cron
Source8:    textonly.filter
Source9:    textonly.ppd
Source10:    cups-rpmlintrc
Source11:    cups.xinetd
Source100:  cups.yaml
Patch0:     cups-no-gzip-man.patch
Patch1:     cups-1.1.16-system-auth.patch
Patch2:     cups-multilib.patch
Patch3:     cups-serial.patch
Patch4:     cups-banners.patch
Patch5:     cups-serverbin-compat.patch
Patch6:     cups-no-export-ssllibs.patch
Patch7:     cups-direct-usb.patch
Patch8:     cups-lpr-help.patch
Patch9:     cups-peercred.patch
Patch10:     cups-pid.patch
Patch11:     cups-page-label.patch
Patch12:     cups-eggcups.patch
Patch13:     cups-getpass.patch
Patch14:     cups-driverd-timeout.patch
Patch15:     cups-strict-ppd-line-length.patch
Patch16:     cups-logrotate.patch
Patch17:     cups-usb-paperout.patch
Patch18:     cups-build.patch
Patch19:     cups-res_init.patch
Patch20:     cups-filter-debug.patch
Patch21:     cups-uri-compat.patch
Patch22:     cups-cups-get-classes.patch
Patch23:     cups-avahi.patch
Patch24:     cups-str3382.patch
Patch25:     cups-0755.patch
Patch26:     cups-EAI_AGAIN.patch
Patch27:     cups-snmp-quirks.patch
Patch28:     cups-hp-deviceid-oid.patch
Patch29:     cups-dnssd-deviceid.patch
Patch30:     cups-ricoh-deviceid-oid.patch
Patch31:     cups-texttops-rotate-page.patch
Patch32:     cups-str3608.patch
Patch33:     cups-str3518.patch
Patch34:     cups-CVE-2010-2941.patch
Patch35:     cups-xinetd.patch
Requires:   dbus >= 0.90
Requires:   tmpwatch
Requires:   udev
Requires:   acl
Requires:  poppler-utils
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(libpng)
BuildRequires:  pkgconfig(gnutls)
#Disabled for slimmer core
#BuildRequires:  pkgconfig(avahi-core)
BuildRequires:  pam-devel
BuildRequires:  pkgconfig
BuildRequires:  libacl-devel
BuildRequires:  make >= 3.80
BuildRequires:  libjpeg-devel
BuildRequires:  libtiff-devel
BuildRequires:  gcc >= 4.0.1
BuildRequires:  poppler-utils
Provides:   /usr/bin/lpq
Provides:   /usr/bin/lpr
Provides:   /usr/bin/lp
Provides:   /usr/bin/cancel
Provides:   /usr/bin/lprm
Provides:   /usr/bin/lpstat
Provides:   lpd = 3.8.15-4
Provides:   lpr = 3.8.15-4
Provides:   cupsddk = 1.2.3-7
Provides:   cupsddk-drivers = 1.2.3-7
Obsoletes:   lpd <= 3.8.15-3
Obsoletes:   lpr <= 3.8.15-3
Obsoletes:   cupsddk < 1.2.3-7
Obsoletes:   cupsddk-drivers < 1.2.3-7


%description
The Common UNIX Printing System provides a portable printing layer for 
UNIX® operating systems. It has been developed by Easy Software Products 
to promote a standard printing solution for all UNIX vendors and users. 
CUPS provides the System V and Berkeley command-line interfaces.



%package libs
Summary:    Common Unix Printing System - libraries
License:    LGPLv2
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libs
The Common UNIX Printing System provides a portable printing layer for 
UNIX® operating systems. It has been developed by Easy Software Products 
to promote a standard printing solution for all UNIX vendors and users. 
CUPS provides the System V and Berkeley command-line interfaces. 
The cups-libs package provides libraries used by applications to use CUPS
natively, without needing the lp/lpr commands.


%package lpd
Summary:    Common Unix Printing System - lpd emulation
Group:      System/Daemons
Requires:   %{name} = %{version}-%{release}
Requires:   xinetd

%description lpd
The Common UNIX Printing System provides a portable printing layer for 
UNIX® operating systems. This is the package that provides standard 
lpd emulation.


%package devel
Summary:    Common Unix Printing System - development environment
License:    LGPLv2
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   gnutls-devel
Requires:   zlib-devel
Provides:   cupsddk-devel = 1.2.3-7
Obsoletes:   cupsddk-devel < 1.2.3-7

%description devel
The Common UNIX Printing System provides a portable printing layer for 
UNIX® operating systems. This is the development package for creating
additional printer drivers, and other CUPS services.



%prep
%setup -q -n %{name}-%{version}

# cups-no-gzip-man.patch
%patch0 -p1
# cups-1.1.16-system-auth.patch
%patch1 -p1
# cups-multilib.patch
%patch2 -p1
# cups-serial.patch
%patch3 -p1
# cups-banners.patch
%patch4 -p1
# cups-serverbin-compat.patch
%patch5 -p1
# cups-no-export-ssllibs.patch
%patch6 -p1
# cups-direct-usb.patch
%patch7 -p1
# cups-lpr-help.patch
%patch8 -p1
# cups-peercred.patch
%patch9 -p1
# cups-pid.patch
%patch10 -p1
# cups-page-label.patch
%patch11 -p1
# cups-eggcups.patch
%patch12 -p1
# cups-getpass.patch
%patch13 -p1
# cups-driverd-timeout.patch
%patch14 -p1
# cups-strict-ppd-line-length.patch
%patch15 -p1
# cups-logrotate.patch
%patch16 -p1
# cups-usb-paperout.patch
%patch17 -p1
# cups-build.patch
%patch18 -p1
# cups-res_init.patch
%patch19 -p1
# cups-filter-debug.patch
%patch20 -p1
# cups-uri-compat.patch
%patch21 -p1
# cups-cups-get-classes.patch
%patch22 -p1
# cups-avahi.patch
%patch23 -p1
# cups-str3382.patch
%patch24 -p1
# cups-0755.patch
%patch25 -p1
# cups-EAI_AGAIN.patch
%patch26 -p1
# cups-snmp-quirks.patch
%patch27 -p1
# cups-hp-deviceid-oid.patch
%patch28 -p1
# cups-dnssd-deviceid.patch
%patch29 -p1
# cups-ricoh-deviceid-oid.patch
%patch30 -p1
# cups-texttops-rotate-page.patch
%patch31 -p1
# cups-str3608.patch
%patch32 -p1
# cups-str3518.patch
%patch33 -p1
# cups-CVE-2010-2941.patch
%patch34 -p1
# cups-xinetd.patch
%patch35 -p1
# >> setup
sed -i -e '1iMaxLogSize 0' conf/cupsd.conf.in

cp %{SOURCE4} cups-lpd.real
perl -pi -e "s,\@LIBDIR\@,%{_libdir},g" cups-lpd.real

# Let's look at the compilation command lines.
perl -pi -e "s,^.SILENT:,," Makedefs.in

# Fix locale code for Norwegian (bug #520379).
mv locale/cups_no.po locale/cups_nb.po

# Rebuild configure script for --enable-avahi.
aclocal -I config-scripts
autoconf -I config-scripts
# << setup

%build
# >> build pre
export CFLAGS="$RPM_OPT_FLAGS -fstack-protector-all -DLDAP_DEPRECATED=1"
# << build pre

%configure --disable-static \
    --with-docdir=%{_datadir}/%{name}/www \
    --enable-debug \
    --with-log-file-perm=0600 \
    --enable-pie \
    --enable-relro \
    --with-pdftops=pdftops \
    --with-dbusdir=%{_sysconfdir}/dbus-1 \
    --disable-avahi \
    --disable-threads \
    --enable-gnutls localedir=%{_datadir}/locale


# >> build post
make %{?jobs:-j%jobs}
# << build post
%install
rm -rf %{buildroot}
# >> install pre
make BUILDROOT=%{buildroot} install
# << install pre

# >> install post
# Serial backend needs to run as root (bug #212577).
chmod 700 $RPM_BUILD_ROOT%{cups_serverbin}/backend/serial

find $RPM_BUILD_ROOT%{_datadir}/cups/model -name "*.ppd" |xargs gzip -n9f


mkdir -p $RPM_BUILD_ROOT%{_datadir}/pixmaps $RPM_BUILD_ROOT%{_sysconfdir}/X11/sysconfig $RPM_BUILD_ROOT%{_sysconfdir}/X11/applnk/System $RPM_BUILD_ROOT%{_sysconfdir}/xinetd.d $RPM_BUILD_ROOT%{_sysconfdir}/logrotate.d $RPM_BUILD_ROOT%{_sysconfdir}/cron.daily
install -c -m 644 %{SOURCE1} $RPM_BUILD_ROOT%{_datadir}/pixmaps
install -c -m 644 %{SOURCE5} $RPM_BUILD_ROOT%{_sysconfdir}/logrotate.d/cups
install -c -m 755 %{SOURCE6} $RPM_BUILD_ROOT%{cups_serverbin}/backend/ncp
install -c -m 755 %{SOURCE7} $RPM_BUILD_ROOT%{_sysconfdir}/cron.daily/cups
install -c -m 755 %{SOURCE8} $RPM_BUILD_ROOT%{cups_serverbin}/filter/textonly
install -c -m 644 %{SOURCE9} $RPM_BUILD_ROOT%{_datadir}/cups/model/textonly.ppd
install -c -m 644 %{SOURCE11} $RPM_BUILD_ROOT%{_sysconfdir}/xinetd.d/cupsd

# Ship a printers.conf file, and a client.conf file.  That way, they get
# their SELinux file contexts set correctly.
touch $RPM_BUILD_ROOT%{_sysconfdir}/cups/printers.conf
touch $RPM_BUILD_ROOT%{_sysconfdir}/cups/classes.conf
touch $RPM_BUILD_ROOT%{_sysconfdir}/cups/client.conf
touch $RPM_BUILD_ROOT%{_sysconfdir}/cups/subscriptions.conf

# This is %%ghost'ed, but needs to be created in %%install anyway.
touch $RPM_BUILD_ROOT%{_sysconfdir}/cups/lpoptions

# LSB 3.2 printer driver directory
mkdir -p $RPM_BUILD_ROOT%{_datadir}/ppd

# Handle https:// device URIs (bug #478677, STR #3122).
ln -s ipp $RPM_BUILD_ROOT%{cups_serverbin}/backend/https

# Remove unshipped files.
rm -rf $RPM_BUILD_ROOT%{_mandir}/cat? $RPM_BUILD_ROOT%{_mandir}/*/cat?
rm -f $RPM_BUILD_ROOT%{_datadir}/applications/cups.desktop
rm -rf $RPM_BUILD_ROOT%{_datadir}/icons

# Install the udev rules.
%{__mkdir_p} %{buildroot}/lib/udev/rules.d
install -m644 %{SOURCE2} \
%{buildroot}/lib/udev/rules.d/70-cups-libusb.rules
# << install post



%post
# >> post
/bin/rm -rf %{_sysconfdir}/cups/certs
rm -f %{_localstatedir}/cache/cups/*.ipp %{_localstatedir}/cache/cups/*.cache
exit 0
# << post

%postun
# >> postun
%triggerin -- samba-client
ln -sf ../../../bin/smbspool %{cups_serverbin}/backend/smb || :
exit 0

%triggerun -- samba-client
[ $2 = 0 ] || exit 0
rm -f %{cups_serverbin}/backend/smb
# << postun



%post libs -p /sbin/ldconfig

%postun libs -p /sbin/ldconfig







%files
%defattr(-,root,root,-)
# >> files
%doc LICENSE.txt README.txt CREDITS.txt CHANGES.txt
/lib/udev/rules.d/70-cups-libusb.rules
%exclude /etc/init.d/cups
%exclude /etc/rc0.d/K36cups
%exclude /etc/rc2.d/K36cups
%exclude /etc/rc2.d/S81cups
%exclude /etc/rc3.d/K36cups
%exclude /etc/rc3.d/S81cups
%exclude /etc/rc5.d/K36cups
%exclude /etc/rc5.d/S81cups
%dir %attr(0755,root,lp) %{_sysconfdir}/cups
%dir %attr(0755,root,lp) /var/run/cups
%dir %attr(0511,lp,sys) /var/run/cups/certs
%verify(not md5 size mtime) %config(noreplace) %attr(0640,root,lp) %{_sysconfdir}/cups/cupsd.conf
%attr(0640,root,lp) %{_sysconfdir}/cups/cupsd.conf.default
%verify(not md5 size mtime) %config(noreplace) %attr(0644,root,lp) %{_sysconfdir}/cups/client.conf
%verify(not md5 size mtime) %config(noreplace) %attr(0600,root,lp) %{_sysconfdir}/cups/classes.conf
%verify(not md5 size mtime) %config(noreplace) %attr(0600,root,lp) %{_sysconfdir}/cups/printers.conf
%verify(not md5 size mtime) %config(noreplace) %attr(0644,root,lp) %{_sysconfdir}/cups/snmp.conf
%verify(not md5 size mtime) %config(noreplace) %attr(0644,root,lp) %{_sysconfdir}/cups/subscriptions.conf
%{_sysconfdir}/cups/interfaces
%verify(not md5 size mtime) %config(noreplace) %attr(0644,root,lp) %{_sysconfdir}/cups/lpoptions
%dir %attr(0755,root,lp) %{_sysconfdir}/cups/ppd
%dir %attr(0700,root,lp) %{_sysconfdir}/cups/ssl
%config(noreplace) %{_sysconfdir}/pam.d/cups
%config(noreplace) %{_sysconfdir}/logrotate.d/cups
%config(noreplace) %{_sysconfdir}/xinetd.d/cupsd
%dir %{_datadir}/%{name}/www
%dir %{_datadir}/%{name}/www/es
%dir %{_datadir}/%{name}/www/eu
%dir %{_datadir}/%{name}/www/ja
%dir %{_datadir}/%{name}/www/pl
%dir %{_datadir}/%{name}/www/ru
%config(noreplace) %{_datadir}/%{name}/www/images
%config(noreplace) %{_datadir}/%{name}/www/*.css
%config(noreplace) %doc %{_datadir}/%{name}/www/index.html
%config(noreplace) %doc %{_datadir}/%{name}/www/help
%config(noreplace) %doc %{_datadir}/%{name}/www/robots.txt
%config(noreplace) %doc %{_datadir}/%{name}/www/de/index.html
%config(noreplace) %doc %{_datadir}/%{name}/www/es/index.html
%config(noreplace) %doc %{_datadir}/%{name}/www/eu/index.html
%config(noreplace) %doc %{_datadir}/%{name}/www/id/index.html
%config(noreplace) %doc %{_datadir}/%{name}/www/it/index.html
%config(noreplace) %doc %{_datadir}/%{name}/www/ja/index.html
%config(noreplace) %doc %{_datadir}/%{name}/www/pl/index.html
%config(noreplace) %doc %{_datadir}/%{name}/www/ru/index.html
# MeeGo: don't start cups on boot
%{_bindir}/cupstestppd
%{_bindir}/cupstestdsc
%{_bindir}/cancel*
%{_bindir}/lp*
%{_bindir}/ppd*
%dir %{cups_serverbin}
%{cups_serverbin}/backend
%{cups_serverbin}/cgi-bin
%dir %{cups_serverbin}/daemon
%{cups_serverbin}/daemon/cups-polld
%{cups_serverbin}/daemon/cups-deviced
%{cups_serverbin}/daemon/cups-driverd
%{cups_serverbin}/notifier
%{cups_serverbin}/filter
%{cups_serverbin}/monitor
%{cups_serverbin}/driver
%{_mandir}/man?/*
%{_sbindir}/*
%dir %{_datadir}/cups
%dir %{_datadir}/cups/banners
%config(noreplace) %{_datadir}/cups/banners/*
%{_datadir}/cups/charsets
%{_datadir}/cups/charmaps
%{_datadir}/cups/data
%{_datadir}/cups/fonts
%{_datadir}/cups/model
%dir %{_datadir}/cups/templates
%config(noreplace) %{_datadir}/cups/templates/*.tmpl
%config(noreplace) %{_datadir}/cups/templates/de/*.tmpl
%config(noreplace) %{_datadir}/cups/templates/es/*.tmpl
%config(noreplace) %{_datadir}/cups/templates/eu/*.tmpl
%config(noreplace) %{_datadir}/cups/templates/id/*.tmpl
%config(noreplace) %{_datadir}/cups/templates/it/*.tmpl
%config(noreplace) %{_datadir}/cups/templates/ja/*.tmpl
%config(noreplace) %{_datadir}/cups/templates/pl/*.tmpl
%config(noreplace) %{_datadir}/cups/templates/ru/*.tmpl
%{_datadir}/locale/*/*.po
%{_datadir}/ppd
%dir %attr(1770,root,lp) /var/spool/cups/tmp
%dir %attr(0710,root,lp) /var/spool/cups
%dir %attr(0755,lp,sys) /var/log/cups
%{_datadir}/pixmaps/cupsprinter.png
%{_sysconfdir}/cron.daily/cups
%{_sysconfdir}/dbus-1/system.d/cups.conf
%{_datadir}/cups/drv
%{_datadir}/cups/examples
%dir %{_datadir}/cups/mime
%config(noreplace) %{_datadir}/cups/mime/mime.types
%config(noreplace) %{_datadir}/cups/mime/mime.convs
%dir %{_datadir}/cups/ppdc
%{_datadir}/cups/ppdc/*.defs
%{_datadir}/cups/ppdc/*.h
# << files


%files libs
%defattr(-,root,root,-)
# >> files libs
%{_libdir}/*.so.*
# << files libs

%files lpd
%defattr(-,root,root,-)
# >> files lpd
%config(noreplace) %{_sysconfdir}/xinetd.d/cups-lpd
%dir %{cups_serverbin}
%dir %{cups_serverbin}/daemon
%{cups_serverbin}/daemon/cups-lpd
# << files lpd

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_bindir}/cups-config
%{_libdir}/*.so
%{_includedir}/cups
# << files devel

